name: quran
description: Qur'an Application.

version: 1.0.1+6

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  quran_uz: ^2.2.1

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.5
  share_plus: ^6.3.2
  converter_uz: ^1.0.1
  flutter_native_splash: ^2.2.19
  meta: ^1.8.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Me-Quran
      fonts:
        - asset: assets/fonts/arabic/Me-Quran-Regular.ttf

    - family: Al-Qalam
      fonts:
        - asset: assets/fonts/arabic/al-qalam-kitab.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
