name: quran
description: Qur'an Application.

version: 1.0.1+6

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  quran_uz: 1.0.5

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  share_plus: ^4.0.10+1
  converter_uz: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Me-Quran
      fonts:
        - asset: assets/fonts/arabic/Me-Quran-Regular.ttf

    - family: Al-Qalam
      fonts:
        - asset: assets/fonts/arabic/al-qalam-kitab.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
